<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Monolog' => array($vendorDir . '/monolog/monolog/src'),
    'Michelf' => array($vendorDir . '/michelf/php-markdown'),
    'Guzzle\\Tests' => array($vendorDir . '/guzzle/guzzle/tests'),
    'Guzzle' => array($vendorDir . '/guzzle/guzzle/src'),
    'Fuel\\Upload' => array($vendorDir . '/fuelphp/upload/src'),
    'Composer\\Installers\\' => array($vendorDir . '/composer/installers/src'),
    'Aws' => array($vendorDir . '/aws/aws-sdk-php/src'),
);
